scrape_configs:
  - job_name: 'riotx'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'RIOT-X'